// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {clicker} from '../models';

export function BeginWindowPick(arg1:string):Promise<void>;

export function CancelWindowPick():Promise<void>;

export function ClearBinding(arg1:string,arg2:number):Promise<void>;

export function CloseProfile(arg1:string):Promise<void>;

export function CreateProfile():Promise<app.ProfileView>;

export function GetHotkeys():Promise<clicker.HotkeyConfig>;

export function GetSnapshot():Promise<app.Snapshot>;

export function RenameProfile(arg1:string,arg2:string):Promise<void>;

export function ResetHotkeys():Promise<clicker.HotkeyConfig>;

export function RestartAsAdministrator():Promise<void>;

export function SetActiveProfile(arg1:string):Promise<void>;

export function SetBinding(arg1:string,arg2:number,arg3:clicker.KeyBinding):Promise<void>;

export function SetHotkeys(arg1:clicker.HotkeyConfig):Promise<void>;

export function StartAll():Promise<clicker.BatchResult>;

export function StartProfile(arg1:string):Promise<void>;

export function StopAll():Promise<void>;

export function StopProfile(arg1:string):Promise<void>;
