// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginWindowPick(arg1) {
  return window['go']['app']['ClickerService']['BeginWindowPick'](arg1);
}

export function CancelWindowPick() {
  return window['go']['app']['ClickerService']['CancelWindowPick']();
}

export function ClearBinding(arg1, arg2) {
  return window['go']['app']['ClickerService']['ClearBinding'](arg1, arg2);
}

export function CloseProfile(arg1) {
  return window['go']['app']['ClickerService']['CloseProfile'](arg1);
}

export function CreateProfile() {
  return window['go']['app']['ClickerService']['CreateProfile']();
}

export function GetHotkeys() {
  return window['go']['app']['ClickerService']['GetHotkeys']();
}

export function GetSnapshot() {
  return window['go']['app']['ClickerService']['GetSnapshot']();
}

export function RenameProfile(arg1, arg2) {
  return window['go']['app']['ClickerService']['RenameProfile'](arg1, arg2);
}

export function ResetHotkeys() {
  return window['go']['app']['ClickerService']['ResetHotkeys']();
}

export function RestartAsAdministrator() {
  return window['go']['app']['ClickerService']['RestartAsAdministrator']();
}

export function SetActiveProfile(arg1) {
  return window['go']['app']['ClickerService']['SetActiveProfile'](arg1);
}

export function SetBinding(arg1, arg2, arg3) {
  return window['go']['app']['ClickerService']['SetBinding'](arg1, arg2, arg3);
}

export function SetHotkeys(arg1) {
  return window['go']['app']['ClickerService']['SetHotkeys'](arg1);
}

export function StartAll() {
  return window['go']['app']['ClickerService']['StartAll']();
}

export function StartProfile(arg1) {
  return window['go']['app']['ClickerService']['StartProfile'](arg1);
}

export function StopAll() {
  return window['go']['app']['ClickerService']['StopAll']();
}

export function StopProfile(arg1) {
  return window['go']['app']['ClickerService']['StopProfile'](arg1);
}
