// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {clicker} from '../models';

export function BeginFollowWindowPick():Promise<void>;

export function BeginMainWindowPick():Promise<void>;

export function CancelWindowPick():Promise<void>;

export function ClearTargets():Promise<void>;

export function GetSnapshot():Promise<app.FollowSyncSnapshot>;

export function RemoveFollowWindow(arg1:number):Promise<void>;

export function SetRules(arg1:clicker.KeyRuleConfig):Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;
