// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginFollowWindowPick() {
  return window['go']['app']['FollowSyncService']['BeginFollowWindowPick']();
}

export function BeginMainWindowPick() {
  return window['go']['app']['FollowSyncService']['BeginMainWindowPick']();
}

export function CancelWindowPick() {
  return window['go']['app']['FollowSyncService']['CancelWindowPick']();
}

export function ClearTargets() {
  return window['go']['app']['FollowSyncService']['ClearTargets']();
}

export function GetSnapshot() {
  return window['go']['app']['FollowSyncService']['GetSnapshot']();
}

export function RemoveFollowWindow(arg1) {
  return window['go']['app']['FollowSyncService']['RemoveFollowWindow'](arg1);
}

export function SetRules(arg1) {
  return window['go']['app']['FollowSyncService']['SetRules'](arg1);
}

export function Start() {
  return window['go']['app']['FollowSyncService']['Start']();
}

export function Stop() {
  return window['go']['app']['FollowSyncService']['Stop']();
}
